#!/bin/sh

# This file is part of Shapes.
#
# Shapes is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Shapes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Shapes.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2008 Gustaf Hendeby

if test "X${srcdir}" == "X"
then
	srcdir="."
fi

OUTPUT=out/FNAME.pdf
LOG=FNAME.log
CORRECT=${srcdir}/FNAME.correct*.pdf

case "$COMPARE" in
yes|'')
  result=1
	for corr in ${CORRECT}
  do
	  if test "$(compare -density 150 -metric AE \
	          ${corr} ${OUTPUT} /dev/null 2>&1)" -eq 0
    then
      result=0
    fi
  done
	;;
*)
	test -f ${OUTPUT} -a ! -f out/FNAME.error
	result=$?
	;;
esac

cat  > ${LOG} <<EOF
*** $0 ***

Expected output :  ${CORRECT}
Output          :  ${OUTPUT}
EOF

if test $result -ne 0
then
	cat >> $LOG <<EOF
Result          :  FAIL
---
EOF
	case "$COMPARE" in
	yes|'')
	for corr in ${CORRECT}
  do
		compare -verbose -density 150 \
		        ${corr} ${OUTPUT} /dev/null >> $LOG 2>&1
  done
		;;
	esac
else
	cat >> $LOG <<EOF
Result          :  PASS
EOF
fi

if test $# -gt 0 && test "$1" -gt 0
then
	cat $LOG
fi

exit $result
