#!/bin/sh

if test "X${srcdir}" == "X"
then
	srcdir="."
fi

OUTPUT=out/FNAME.pdf
LOG=FNAME.log
CORRECT=${srcdir}/FNAME.correct*.pdf

case "$COMPARE" in
yes|'')
  result=1
	for corr in ${CORRECT}
  do
	  if test "$(compare -density 150 -metric AE \
	          ${corr} ${OUTPUT} /dev/null 2>&1)" -eq 0
    then
      result=0
    fi
  done
	;;
*)
	test -f ${OUTPUT} -a ! -f out/FNAME.error
	result=$?
	;;
esac

cat  > ${LOG} <<EOF
*** $0 ***

Expected output :  ${CORRECT}
Output          :  ${OUTPUT}
EOF

if test $result -ne 0
then
	cat >> $LOG <<EOF
Result          :  FAIL
---
EOF
	case "$COMPARE" in
	yes|'')
	for corr in ${CORRECT}
  do
		compare -verbose -density 150 \
		        ${corr} ${OUTPUT} /dev/null >> $LOG 2>&1
  done
		;;
	esac
else
	cat >> $LOG <<EOF
Result          :  PASS
EOF
fi

if test $# -gt 0 && test "$1" -gt 0
then
	cat $LOG
fi

exit $result
