#!/bin/sh

# This file is part of Shapes.
#
# Shapes is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Shapes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Shapes.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2008 Gustaf Hendeby

if test "X${srcdir}" == "X"
then
	srcdir="."
fi

OUTPUT=FNAME.out
LOG=FNAME.log
CORRECT=${srcdir}/FNAME.correct

cmp ${CORRECT} ${OUTPUT} > /dev/null 2>&1
result=$?

cat  > ${LOG} <<EOF
*** $0 ***

Expected output :  ${CORRECT}
Output          :  ${OUTPUT}
EOF

if test $result -ne 0
then
	cat >> $LOG <<EOF
Result          :  FAIL
---
EOF
	diff -u ${CORRECT} ${OUTPUT} >> ${LOG} 2>&1
else
	cat >> $LOG <<EOF
Result          :  PASS
EOF
fi

if test $# -gt 0 && test "$1" -gt 0
then
	cat $LOG
fi

exit $result
