#!/bin/sh

if test "X${srcdir}" == "X"
then
	srcdir="."
fi

OUTPUT=FNAME.out
LOG=FNAME.log
CORRECT=${srcdir}/FNAME.correct

cmp ${CORRECT} ${OUTPUT} > /dev/null 2>&1
result=$?

cat  > ${LOG} <<EOF
*** $0 ***

Expected output :  ${CORRECT}
Output          :  ${OUTPUT}
EOF

if test $result -ne 0
then
	cat >> $LOG <<EOF
Result          :  FAIL
---
EOF
	diff -u ${CORRECT} ${OUTPUT} >> ${LOG} 2>&1
else
	cat >> $LOG <<EOF
Result          :  PASS
EOF
fi

if test $# -gt 0 && test "$1" -gt 0
then
	cat $LOG
fi

exit $result