#!/bin/sh

cat exscripts/GPL-head exscripts/copyright-tidefelt > GPL-head-xml; cat exscripts/comment-xml.ex | ex GPL-head-xml

for i in `grep -l '<?xml' *.xml *.sxml *.xsl formats/*.xml formats/*.sxml formats/*.xsl`; do
  echo Fixing $i
  cat exscripts/instrument-xml.ex | ex -sC $i
done

for i in `grep -L '<?xml' *.xml *.sxml *.xsl formats/*.xml formats/*.sxml formats/*.xsl`; do
  echo Fixing $i
  mv $i tmp; cat GPL-head-xml tmp > $i
done

rm GPL-head-xml tmp
