#!/bin/sh

cat exscripts/GPL-head exscripts/copyright-tidefelt > GPL-head-c; cat exscripts/comment-c.ex | ex GPL-head-c

for i in `ls *.h *.cc *.ll *.yy`; do
  echo Fixing $i
  mv $i tmp; cat GPL-head-c tmp > $i
done

rm GPL-head-c tmp
