#!/bin/sh

for i in `ls ../../examples/features/*.shape ../../examples/showcase/*.shape ../../examples/problems/*.shape ../../examples/misc/*.shape ../../examples/applications/*.shape ../../examples/doc/*.shape ../../test/text/*.shape ../../test/graphics/*.shape ../../resources/extensions/*.shext`; do
  echo Fixing $i
#  ex -sC $i < exshapessource
  ex -sC $i < ../../resources/version-converters/0.4.3
done
