#ifndef config_h
#define config_h

/*
 * This file will be generated by a ./configure script in the future, but until then
 * we just put that kind of stuff here manually.
 */


#ifdef ICONV_IS_POSIX
#  define ICONV_CAST( ptr ) const_cast< char ** >( ptr )
#else
#  define ICONV_CAST( ptr ) ptr
#endif


#endif
