#!/bin/sh

# This file is part of Shapes.
#
# Shapes is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Shapes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Shapes.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2008 Gustaf Hendeby

LF='
'
if test $# -lt 1
then
	DIR='..'
else
	DIR=$1
fi

SVF=SHAPES-VERSION-FILE
SVF_DEF=$DIR/VERSION
SVF_DIST=version
VN=$(sed -e '2,$ d' < $SVF_DEF)
VD=$(date +"%Y-%m-%d %T %z")

if test -f $SVF_DIST
then
	VN=$(sed -e '/NUMBER/! d' -e 's/VERSION_NUMBER := //' < $SVF_DIST)
	VD=$(sed -e '/DATE/! d' -e 's/VERSION_DATE := //' < $SVF_DIST)
elif test -d $DIR/.git &&
	VN=$(cd ${DIR} && git describe --abbrev=4 HEAD 2>/dev/null) &&
	case "$VN" in
	*$LF*) (exit 1) ;;
	[0-9]*) : ;;
	esac
then
	if test -z "$(cd ${DIR} && git diff-index --name-only HEAD)"
	then
		VD=$(cd ${DIR} && git show --quiet --pretty="format:%ci" HEAD)
	else
		VN="$VN-dirty"
	fi
fi

if test -r $SVF
then
	FVN=$(sed -e '/NUMBER/! d' -e 's/VERSION_NUMBER := //' < $SVF)
	FVD=$(sed -e '/DATE/! d' -e 's/VERSION_DATE := //' < $SVF)
else
	FVN=undef
	FVD=undef
fi

VDcmp=$(echo "$VD" | sed -e 's/\([0-9]\{2\}:[0-9]\{2\}\):[0-9.]*/\1/g')
FVDcmp=$(echo "$FVD" | sed -e 's/\([0-9]\{2\}:[0-9]\{2\}\):[0-9.]*/\1/g')
test "$VDcmp" = "$FVDcmp" -a "$VN" = "$FVN" || {
	echo >&2 "\
VERSION_NUMBER := ${VN}
VERSION_DATE := ${VD}"
	echo "\
VERSION_NUMBER := ${VN}
VERSION_DATE := ${VD}" > $SVF
}
