## Please make sure that index is made last, since making the parts will ensure that meta data about file locations is generated.

all:
	cd man; make
	cd syntax; make
	cd bindings; make
	cd dynamic; make
	cd types; make
	cd tutorial; make
	cd index; make
